---
- hosts: win
  tasks:
  - name: Download apache msi
    win_get_url:
      url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
      dest: c:\httpd-2.2.25-win32-x86-no_ssl.msi
  - name: Install MSI Package
    win_package:
      path: c:\httpd-2.2.25-win32-x86-no_ssl.msi
      state: present
